services:
  - type: web
    name: aurrex-backend
    runtime: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: CLIENT_URL
        value: https://aurrex-frontend.onrender.com
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false

  - type: static
    name: aurrex-frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://aurrex-backend.onrender.com
