import{useState,useEffect,useRef,useCallback}from'react'
import{useParams,useNavigate}from'react-router-dom'
import{ArrowLeft,Save,Plus,Trash2,Download,Image}from'lucide-react'
import toast from'react-hot-toast'
import api from'../../lib/axios'
import{n,fmt}from'../../lib/utils'
import CalcInput from'../../components/CalcInput'
import{generateConnectionPDF}from'../../lib/pdfExport'
const emptyConn=()=>({name:'',image:'',type:'Staff',connectionMode:'manager',notes:'',gemEntry:[],staffPaymentEntry:[],paymentGiven:[],paymentReceived:[]})
function SC({title,children,action}){return(<div className="section-card"><div className="flex items-center justify-between mb-4"><h2 className="font-bold">{title}</h2>{action}</div>{children}</div>)}
export default function ManagerConnectionDetail(){
  const{id}=useParams();const isNew=id==='new'||!id;const navigate=useNavigate()
  const[conn,setConn]=useState(emptyConn());const[loading,setLoading]=useState(!isNew);const[saving,setSaving]=useState(false);const[savedId,setSavedId]=useState(null)
  const fileRef=useRef();const debRef=useRef();const cid=savedId||(isNew?null:id)
  useEffect(()=>{if(isNew)return;api.get('/connections/'+id).then(({data})=>setConn(data.connection)).catch(()=>toast.error('Failed')).finally(()=>setLoading(false))},[id])
  const autoSave=useCallback(async(data)=>{if(!cid)return;clearTimeout(debRef.current);debRef.current=setTimeout(async()=>{try{await api.put('/connections/'+cid,data)}catch{}},800)},[cid])
  const set=(f,v)=>setConn(prev=>{const next={...prev,[f]:v};autoSave(next);return next})
  const upd=(fn)=>setConn(prev=>{const next=fn(prev);autoSave(next);return next})
  const addRow=(tbl,blank)=>upd(p=>({...p,[tbl]:[...(p[tbl]||[]),blank]}))
  const delRow=(tbl,i)=>upd(p=>({...p,[tbl]:p[tbl].filter((_,idx)=>idx!==i)}))
  const setRow=(tbl,i,f,v)=>upd(p=>{const rows=[...(p[tbl]||[])];rows[i]={...rows[i],[f]:v};return{...p,[tbl]:rows}})
  const setGemRow=(i,f,v)=>upd(p=>{const rows=[...(p.gemEntry||[])];rows[i]={...rows[i],[f]:v};rows[i].amount=n(rows[i].gem)*n(rows[i].pricePerGem);return{...p,gemEntry:rows}})
  let sumAmt=0
  if(conn.type==='Staff')sumAmt=(conn.gemEntry||[]).reduce((s,r)=>s+n(r.amount),0)-(conn.staffPaymentEntry||[]).reduce((s,r)=>s+n(r.amount),0)
  else if(conn.type==='Payment')sumAmt=(conn.paymentReceived||[]).reduce((s,r)=>s+n(r.amount),0)-(conn.paymentGiven||[]).reduce((s,r)=>s+n(r.amount),0)
  const handleSave=async()=>{if(!conn.name)return toast.error('Name required');setSaving(true);try{if(cid){await api.put('/connections/'+cid,conn);toast.success('Saved!')}else{const{data}=await api.post('/connections',conn);setSavedId(data.connection._id);navigate('/manager/connections/'+data.connection._id,{replace:true});toast.success('Created!')}}catch(err){toast.error(err.response?.data?.error||'Failed')}finally{setSaving(false)}}
  const uploadImg=async(file)=>{if(!cid)return toast.error('Save first');const fd=new FormData();fd.append('image',file);try{const{data}=await api.post('/connections/'+cid+'/image',fd);set('image',data.imageUrl);toast.success('Uploaded')}catch{toast.error('Failed')}}
  const PayTbl=({title,tbl})=>(<SC title={title}action={<button onClick={()=>addRow(tbl,{amount:0,date:'',note:''})}className="btn-violet text-xs px-3 py-1.5"><Plus className="w-3.5 h-3.5"/>Add</button>}><div className="overflow-x-auto rounded-xl border border-slate-200 dark:border-zinc-700"><table className="w-full text-sm"><thead><tr className="bg-slate-50 dark:bg-zinc-800 border-b border-slate-200 dark:border-zinc-700">{['Amount','Note','Date',''].map(h=><th key={h}className="table-header text-left py-2.5 px-4">{h}</th>)}</tr></thead><tbody>{(conn[tbl]||[]).map((row,i)=>(<tr key={i}className="border-b border-slate-100 dark:border-zinc-800 last:border-0"><td className="py-2 px-3"><CalcInput className="input-base text-xs py-1.5"value={row.amount}onChange={v=>setRow(tbl,i,'amount',v)}/></td><td className="py-2 px-3"><input className="input-base text-xs py-1.5"value={row.note||''}onChange={e=>setRow(tbl,i,'note',e.target.value)}/></td><td className="py-2 px-3"><input className="input-base text-xs py-1.5"type="date"value={row.date}onChange={e=>setRow(tbl,i,'date',e.target.value)}/></td><td className="py-2 px-3"><button onClick={()=>delRow(tbl,i)}className="text-red-400 p-1"><Trash2 className="w-3.5 h-3.5"/></button></td></tr>))}{(conn[tbl]||[]).length===0&&<tr><td colSpan={4}className="py-8 text-center text-slate-400 text-sm">No entries</td></tr>}</tbody></table></div></SC>)
  if(loading)return<div className="p-6 space-y-4 max-w-4xl mx-auto">{[1,2,3].map(i=><div key={i}className="h-20 rounded-2xl bg-slate-100 dark:bg-zinc-800 animate-pulse"/>)}</div>
  return(
    <div className="p-4 sm:p-6 max-w-4xl mx-auto">
      <div className="flex flex-wrap items-center justify-between gap-3 mb-6"><div className="flex items-center gap-3"><button onClick={()=>navigate('/manager/connections')}className="w-9 h-9 flex items-center justify-center rounded-xl bg-slate-100 dark:bg-zinc-800"><ArrowLeft className="w-4 h-4"/></button><h1 className="text-2xl font-bold"style={{fontFamily:'Playfair Display,serif'}}>{isNew?'New Connection':conn.name}</h1></div><div className="flex gap-2">{!isNew&&<button onClick={()=>generateConnectionPDF(conn,{amount:sumAmt,gold:0})}className="btn-secondary"><Download className="w-4 h-4"/>PDF</button>}<button onClick={handleSave}disabled={saving}className="btn-violet min-w-[80px]"><Save className="w-4 h-4"/>{saving?'Saving…':'Save'}</button></div></div>
      <SC title="Connection Details"><div className="flex flex-wrap items-start gap-5"><div onClick={()=>fileRef.current?.click()}className="w-20 h-20 rounded-2xl border-2 border-dashed border-slate-300 dark:border-zinc-600 flex items-center justify-center cursor-pointer overflow-hidden hover:border-violet-500 transition-colors shrink-0">{conn.image?<img src={conn.image}className="w-full h-full object-cover"alt={conn.name}/>:<div className="text-center text-slate-400"><Image className="w-6 h-6 mx-auto"/><span className="text-xs">Photo</span></div>}</div><input ref={fileRef}type="file"accept="image/*"className="hidden"onChange={e=>e.target.files[0]&&uploadImg(e.target.files[0])}/><div className="flex-1 grid grid-cols-1 sm:grid-cols-2 gap-4"><div><label className="label">Name *</label><input className="input-base"value={conn.name}onChange={e=>set('name',e.target.value)}/></div><div><label className="label">Type *</label><select className="input-base"value={conn.type}onChange={e=>set('type',e.target.value)}><option>Staff</option><option>Payment</option></select></div></div></div></SC>
      <div className="manager-box mb-5"><h2 className="font-bold text-violet-800 dark:text-violet-300 mb-3">Account Summary</h2><p className="text-xs text-violet-700 dark:text-violet-400 mb-1">Amount (Rs.)</p><p className={`text-2xl font-bold ${sumAmt>=0?'text-emerald-700':'text-red-600'}`}>Rs.{fmt(sumAmt)}</p></div>
      {conn.type==='Staff'&&<><SC title="Gem Entry"action={<button onClick={()=>addRow('gemEntry',{setName:'',gem:0,pricePerGem:0,amount:0,date:''})}className="btn-violet text-xs px-3 py-1.5"><Plus className="w-3.5 h-3.5"/>Add</button>}><div className="overflow-x-auto rounded-xl border border-slate-200 dark:border-zinc-700"><table className="w-full text-sm"style={{minWidth:'520px'}}><thead><tr className="bg-slate-50 dark:bg-zinc-800 border-b border-slate-200 dark:border-zinc-700">{['Set Name','Gems','Price/Gem','Amount','Date',''].map(h=><th key={h}className="table-header text-left py-2.5 px-3">{h}</th>)}</tr></thead><tbody>{(conn.gemEntry||[]).map((row,i)=>(<tr key={i}className="border-b border-slate-100 dark:border-zinc-800 last:border-0"><td className="py-2 px-2"><input className="input-base text-xs py-1.5 w-28"value={row.setName}onChange={e=>setGemRow(i,'setName',e.target.value)}/></td><td className="py-2 px-2"><CalcInput className="input-base text-xs py-1.5 w-16"value={row.gem}onChange={v=>setGemRow(i,'gem',v)}/></td><td className="py-2 px-2"><CalcInput className="input-base text-xs py-1.5 w-20"value={row.pricePerGem}onChange={v=>setGemRow(i,'pricePerGem',v)}/></td><td className="py-2 px-3"><span className="bg-amber-100 dark:bg-amber-900/20 text-amber-700 dark:text-amber-400 font-bold text-xs px-2 py-1 rounded-lg">Rs.{fmt(row.amount)}</span></td><td className="py-2 px-2"><input className="input-base text-xs py-1.5 w-28"type="date"value={row.date}onChange={e=>setGemRow(i,'date',e.target.value)}/></td><td className="py-2 px-2"><button onClick={()=>delRow('gemEntry',i)}className="text-red-400 p-1"><Trash2 className="w-3.5 h-3.5"/></button></td></tr>))}</tbody></table></div></SC><PayTbl title="Payment Entry"tbl="staffPaymentEntry"/></>}
      {conn.type==='Payment'&&<><PayTbl title="Payment Given"tbl="paymentGiven"/><PayTbl title="Payment Received"tbl="paymentReceived"/></>}
      <SC title="Notes"><textarea className="input-base min-h-[80px] resize-y"value={conn.notes}onChange={e=>set('notes',e.target.value)}/></SC>
    </div>
  )
}