import{useState,useEffect,useRef,useCallback}from'react'
import{useParams,useNavigate}from'react-router-dom'
import{ArrowLeft,Save,Plus,Trash2,Download,Image}from'lucide-react'
import toast from'react-hot-toast'
import api from'../../lib/axios'
import{n,fmt}from'../../lib/utils'
import CalcInput from'../../components/CalcInput'
import{generateStaffPDF}from'../../lib/pdfExport'
const emptyConn=()=>({name:'',image:'',type:'Boss',connectionMode:'staff',notes:'',gemEntry:[],staffPaymentEntry:[]})
export default function StaffConnectionDetail(){
  const{id}=useParams();const isNew=id==='new'||!id;const navigate=useNavigate()
  const[conn,setConn]=useState(emptyConn());const[loading,setLoading]=useState(!isNew);const[saving,setSaving]=useState(false);const[savedId,setSavedId]=useState(null)
  const fileRef=useRef();const debRef=useRef();const cid=savedId||(isNew?null:id)
  useEffect(()=>{if(isNew)return;api.get('/connections/'+id).then(({data})=>setConn(data.connection)).catch(()=>toast.error('Failed')).finally(()=>setLoading(false))},[id])
  const autoSave=useCallback(async(data)=>{if(!cid)return;clearTimeout(debRef.current);debRef.current=setTimeout(async()=>{try{await api.put('/connections/'+cid,data)}catch{}},800)},[cid])
  const set=(f,v)=>setConn(prev=>{const next={...prev,[f]:v};autoSave(next);return next})
  const upd=(fn)=>setConn(prev=>{const next=fn(prev);autoSave(next);return next})
  const addGem=()=>upd(p=>({...p,gemEntry:[...(p.gemEntry||[]),{setName:'',gem:0,pricePerGem:0,amount:0,date:''}]}))
  const delGem=(i)=>upd(p=>({...p,gemEntry:p.gemEntry.filter((_,idx)=>idx!==i)}))
  const setGem=(i,f,v)=>upd(p=>{const rows=[...(p.gemEntry||[])];rows[i]={...rows[i],[f]:v};rows[i].amount=n(rows[i].gem)*n(rows[i].pricePerGem);return{...p,gemEntry:rows}})
  const addPay=()=>upd(p=>({...p,staffPaymentEntry:[...(p.staffPaymentEntry||[]),{amount:0,date:'',note:''}]}))
  const delPay=(i)=>upd(p=>({...p,staffPaymentEntry:p.staffPaymentEntry.filter((_,idx)=>idx!==i)}))
  const setPay=(i,f,v)=>upd(p=>{const rows=[...(p.staffPaymentEntry||[])];rows[i]={...rows[i],[f]:v};return{...p,staffPaymentEntry:rows}})
  const gemTotal=(conn.gemEntry||[]).reduce((s,r)=>s+n(r.amount),0)
  const paidTotal=(conn.staffPaymentEntry||[]).reduce((s,r)=>s+n(r.amount),0)
  const balance=gemTotal-paidTotal
  const handleSave=async()=>{if(!conn.name)return toast.error('Name required');setSaving(true);try{if(cid){await api.put('/connections/'+cid,conn);toast.success('Saved!')}else{const{data}=await api.post('/connections',conn);setSavedId(data.connection._id);navigate('/staff/connections/'+data.connection._id,{replace:true});toast.success('Created!')}}catch(err){toast.error(err.response?.data?.error||'Failed')}finally{setSaving(false)}}
  const uploadImg=async(file)=>{if(!cid)return toast.error('Save first');const fd=new FormData();fd.append('image',file);try{const{data}=await api.post('/connections/'+cid+'/image',fd);set('image',data.imageUrl);toast.success('Uploaded')}catch{toast.error('Failed')}}
  const handlePDF=()=>generateStaffPDF(conn,{gemTotal,paidTotal,balance})
  if(loading)return<div className="p-6 space-y-4 max-w-3xl mx-auto">{[1,2,3].map(i=><div key={i}className="h-20 rounded-2xl bg-slate-100 dark:bg-zinc-800 animate-pulse"/>)}</div>
  return(
    <div className="p-4 sm:p-6 max-w-3xl mx-auto">
      <div className="flex flex-wrap items-center justify-between gap-3 mb-6">
        <div className="flex items-center gap-3"><button onClick={()=>navigate('/staff/connections')}className="w-9 h-9 flex items-center justify-center rounded-xl bg-slate-100 dark:bg-zinc-800 hover:bg-slate-200 dark:hover:bg-zinc-700"><ArrowLeft className="w-4 h-4"/></button><div><h1 className="text-xl font-bold"style={{fontFamily:'Playfair Display,serif'}}>{isNew?'New Boss':conn.name}</h1><p className="text-xs text-blue-500 font-medium">Staff Mode</p></div></div>
        <div className="flex gap-2">{!isNew&&<button onClick={handlePDF}className="btn-secondary text-sm"><Download className="w-4 h-4"/>PDF</button>}<button onClick={handleSave}disabled={saving}className="btn-blue min-w-[80px]"><Save className="w-4 h-4"/>{saving?'Saving…':'Save'}</button></div>
      </div>
      <div className="section-card"><h2 className="font-bold mb-4">Boss Details</h2><div className="flex flex-wrap items-start gap-5"><div onClick={()=>fileRef.current?.click()}className="w-20 h-20 rounded-2xl border-2 border-dashed border-slate-300 dark:border-zinc-600 flex items-center justify-center cursor-pointer overflow-hidden hover:border-blue-500 transition-colors shrink-0">{conn.image?<img src={conn.image}className="w-full h-full object-cover"alt={conn.name}/>:<div className="text-center text-slate-400"><Image className="w-6 h-6 mx-auto"/><span className="text-xs">Photo</span></div>}</div><input ref={fileRef}type="file"accept="image/*"className="hidden"onChange={e=>e.target.files[0]&&uploadImg(e.target.files[0])}/><div className="flex-1"><label className="label">Boss Name *</label><input className="input-base"value={conn.name}onChange={e=>set('name',e.target.value)}/></div></div></div>
      <div className="staff-box mb-5"><h2 className="font-bold text-blue-800 dark:text-blue-300 mb-4">Account Summary</h2><div className="grid grid-cols-1 sm:grid-cols-3 gap-4"><div className="bg-white/70 dark:bg-zinc-800/50 rounded-xl p-3 border border-blue-100 dark:border-blue-800"><p className="text-xs text-slate-500 mb-1">Gem Work</p><p className="text-xl font-bold">Rs.{fmt(gemTotal)}</p></div><div className="bg-white/70 dark:bg-zinc-800/50 rounded-xl p-3 border border-blue-100 dark:border-blue-800"><p className="text-xs text-slate-500 mb-1">Received</p><p className="text-xl font-bold text-emerald-600">Rs.{fmt(paidTotal)}</p></div><div className={`rounded-xl p-3 border ${balance>=0?'bg-emerald-50 dark:bg-emerald-900/20 border-emerald-200':'bg-red-50 dark:bg-red-900/20 border-red-200'}`}><p className="text-xs text-slate-500 mb-1">Balance</p><p className={`text-xl font-bold ${balance>=0?'text-emerald-700':'text-red-600'}`}>Rs.{fmt(balance)}</p></div></div></div>
      <div className="section-card"><div className="flex items-center justify-between mb-4"><h2 className="font-bold">Gem Entry</h2><button onClick={addGem}className="btn-blue text-xs px-3 py-1.5"><Plus className="w-3.5 h-3.5"/>Add</button></div><div className="overflow-x-auto rounded-xl border border-slate-200 dark:border-zinc-700"><table className="w-full text-sm"style={{minWidth:'520px'}}><thead><tr className="bg-slate-50 dark:bg-zinc-800 border-b border-slate-200 dark:border-zinc-700">{['Set Name','Gems','Price/Gem','Amount','Date',''].map(h=><th key={h}className="table-header text-left py-2.5 px-3">{h}</th>)}</tr></thead><tbody>{(conn.gemEntry||[]).map((row,i)=>(<tr key={i}className="border-b border-slate-100 dark:border-zinc-800 last:border-0"><td className="py-2 px-2"><input className="input-base text-xs py-1.5 w-28"value={row.setName}onChange={e=>setGem(i,'setName',e.target.value)}/></td><td className="py-2 px-2"><CalcInput className="input-base text-xs py-1.5 w-16"value={row.gem}onChange={v=>setGem(i,'gem',v)}/></td><td className="py-2 px-2"><CalcInput className="input-base text-xs py-1.5 w-20"value={row.pricePerGem}onChange={v=>setGem(i,'pricePerGem',v)}/></td><td className="py-2 px-3"><span className="bg-amber-100 dark:bg-amber-900/20 text-amber-700 dark:text-amber-400 font-bold text-xs px-2 py-1 rounded-lg">Rs.{fmt(row.amount)}</span></td><td className="py-2 px-2"><input className="input-base text-xs py-1.5 w-28"type="date"value={row.date}onChange={e=>setGem(i,'date',e.target.value)}/></td><td className="py-2 px-2"><button onClick={()=>delGem(i)}className="text-red-400 p-1"><Trash2 className="w-3.5 h-3.5"/></button></td></tr>))}<tr className="bg-slate-50 dark:bg-zinc-800/60"><td colSpan={3}className="py-2.5 px-4 text-xs font-bold">Total</td><td className="py-2.5 px-3 font-mono font-bold text-sm text-amber-600">Rs.{fmt(gemTotal)}</td><td colSpan={2}/></tr></tbody></table></div></div>
      <div className="section-card"><div className="flex items-center justify-between mb-4"><h2 className="font-bold">Payment Entry</h2><button onClick={addPay}className="btn-blue text-xs px-3 py-1.5"><Plus className="w-3.5 h-3.5"/>Add</button></div><div className="overflow-x-auto rounded-xl border border-slate-200 dark:border-zinc-700"><table className="w-full text-sm"><thead><tr className="bg-slate-50 dark:bg-zinc-800 border-b border-slate-200 dark:border-zinc-700">{['Amount','Note','Date',''].map(h=><th key={h}className="table-header text-left py-2.5 px-4">{h}</th>)}</tr></thead><tbody>{(conn.staffPaymentEntry||[]).map((row,i)=>(<tr key={i}className="border-b border-slate-100 dark:border-zinc-800 last:border-0"><td className="py-2 px-3"><CalcInput className="input-base text-xs py-1.5"value={row.amount}onChange={v=>setPay(i,'amount',v)}/></td><td className="py-2 px-3"><input className="input-base text-xs py-1.5"value={row.note||''}onChange={e=>setPay(i,'note',e.target.value)}/></td><td className="py-2 px-3"><input className="input-base text-xs py-1.5"type="date"value={row.date}onChange={e=>setPay(i,'date',e.target.value)}/></td><td className="py-2 px-3"><button onClick={()=>delPay(i)}className="text-red-400 p-1"><Trash2 className="w-3.5 h-3.5"/></button></td></tr>))}{(conn.staffPaymentEntry||[]).length>0&&<tr className="bg-slate-50 dark:bg-zinc-800/60"><td className="py-2.5 px-4 font-mono font-bold text-sm text-emerald-600">Rs.{fmt(paidTotal)}</td><td className="py-2.5 px-4 text-xs font-bold">Total</td><td colSpan={2}/></tr>}</tbody></table></div></div>
      <div className="section-card"><h2 className="font-bold mb-3">Notes</h2><textarea className="input-base min-h-[80px] resize-y"value={conn.notes}onChange={e=>set('notes',e.target.value)}/></div>
    </div>
  )
}